title = "Onebom"
baseURL = 'https://hba.sid.one/'

# This is what goes in <html lang="">
languageCode = 'ko-kr'

# This defines how dates are formatted
defaultContentLanguage = "ko"

# Enable emojis globally
enableEmoji = true
ignoreErrors = ["additional-script-loading-error"] # ignore error of loading additional scripts.

# traditional way: theme component resides in directory 'themes'
theme = "hugo-blog-awesome"

[services]
# To enable Google Analytics 4 (gtag.js) provide G-MEASUREMENT_ID below.
# To disable Google Analytics, simply leave the field empty or remove the next two lines
  [services.googleAnalytics]
    id = '' # G-MEASUREMENT_ID

# To enable Disqus comments, provide Disqus Shortname below.
# To disable Disqus comments, simply leave the field empty or remove the next two lines
  [services.disqus]
    shortname = ''

# set markup.highlight.noClasses=false to enable code highlight
[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true
	[markup.tableOfContents]
		startLevel = 2 # ToC starts from H2
		endLevel = 3 # ToC ends at H4
		ordered = false # generates <ul> instead of <ol>

############################## Korean language ################################
[Languages.ko]
  languageName = "Korean"
  languageCode = "ko-kr"
  contentDir = "content/ko"
  weight = 1

  [Languages.ko.menu]
  #[[Languages.ko.menu.main]]
  #  pageRef="/"
  #  name = 'Home'
  #  url = '/'
  #  weight = 10
  [[Languages.ko.menu.main]]
    pageRef="about"
    name = 'about'
    url = '/about/'
    weight = 20
  [[Languages.ko.menu.main]]
    pageRef="posts"
    name = 'Posts'
    url = '/posts/'
    weight = 30
  

[Languages.ko.params]
  sitename = "Awesome hugo blog"
  defaultColor = "dark" # set color mode: dark, light, auto
  description = "Minimal Hugo blog theme with light and dark mode support"
  mainSections = ['posts']
  toc = true # set to false to disable table of contents 'globally'
  tocOpen = false # set to true to open table of contents by default
  goToTop = true # set to false to disable 'go to top' button
  dateFormat = "2006ë…„ 1ì›” 2ì¼" # date format used to show dates on various pages. If nothing is specified, then "2 Jan 2006" format is used.
  rssFeedDescription = "summary" # available options: 1) summary 2) full

[Languages.ko.params.author]
  avatar = "avatar.jpg" # put the file in assets folder; also ensure that image has same height and width
  intro = "Welcome to Onebom's blog"
  name = "Sidharth R"
  description = """ì•ˆë…•í•˜ì„¸ìš”ğŸ‘‹ í˜„ì¬ MIDASì—ì„œ ì„ì‚¬ì—°êµ¬ì›ìœ¼ë¡œ video generationì„ ì—°êµ¬í•˜ê³  ìˆìŠµë‹ˆë‹¤.
Computer vision, Generative model, Diffusionë“±ì˜ ì£¼ì œë¥¼ ì—°êµ¬í•˜ë©° ì•Œê²Œëœ ì‚¬ì‹¤ê³¼ ê²½í—˜ì„ 
ê³µìœ í•˜ë ¤ê³  í•©ë‹ˆë‹¤:) """

# Allow to override webmanifest options
[Languages.ko.params.webmanifest]
  name = "sitename" # will use "params.sitename" or "title" by default
  short_name = "sitename" # same as name
  start_url = "/" # will use homepage url by default
  theme_color = "#434648" # default is "#434648" (base color of text). Also will override html `<meta name="theme-color" />`
  background_color = "#fff" # by default depend on "params.defaultColor" for "light" or "auto" will be set to "#fff" for dark will be "#131418" (color of dark mode background)
  display = "standalone"

###################################################################

# Allow to override `browserconfig.xml` params (configuration for windows embedded browsers)
[params.browserconfig]
  TileColor = "#2d89ef" # default windows 10 blue tile color

[[params.socialIcons]]
name = "github"
url = "https://github.com/onebom"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com"

[[params.socialIcons]]
name = "Rss"
url = "/index.xml"